/***************************************************************************
 * The contents of this file were generated with Amplify Studio.           *
 * Please refrain from making any modifications to this file.              *
 * Any changes to this file will be overwritten when running amplify pull. *
 **************************************************************************/

/* eslint-disable */
import * as React from "react";
import { getOverrideProps } from "./utils";
import { Image, Text, View } from "@aws-amplify/ui-react";
export default function CheckPage(props) {
  const { mainImage, overrides, ...rest } = props;
  return (
    <View
      width="411px"
      height="579px"
      display="block"
      gap="unset"
      alignItems="unset"
      justifyContent="unset"
      position="relative"
      padding="0px 0px 0px 0px"
      {...getOverrideProps(overrides, "CheckPage")}
      {...rest}
    >
      <View
        width="304px"
        height="440px"
        display="block"
        gap="unset"
        alignItems="unset"
        justifyContent="unset"
        position="absolute"
        top="11.4%"
        bottom="12.61%"
        left="13.38%"
        right="12.65%"
        padding="0px 0px 0px 0px"
        backgroundColor="rgba(252,228,98,1)"
        {...getOverrideProps(overrides, "check-photobase")}
      ></View>
      <Text
        fontFamily="UD Digi Kyokasho NK-B"
        fontSize="13px"
        fontWeight="700"
        color="rgba(0,0,0,1)"
        lineHeight="15.03759765625px"
        textAlign="left"
        display="block"
        direction="column"
        justifyContent="unset"
        width="unset"
        height="unset"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="67.01%"
        bottom="30.4%"
        left="59.37%"
        right="31.14%"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="連絡先"
        {...getOverrideProps(overrides, "check-contact")}
      ></Text>
      <View
        width="318px"
        height="38px"
        display="block"
        gap="unset"
        alignItems="unset"
        justifyContent="unset"
        position="absolute"
        top="93.44%"
        bottom="0%"
        left="11.19%"
        right="11.44%"
        padding="0px 0px 0px 0px"
        {...getOverrideProps(overrides, "check-caution608349")}
      >
        <Text
          fontFamily="Abhaya Libre ExtraBold"
          fontSize="16px"
          fontWeight="800"
          color="rgba(0,0,0,1)"
          lineHeight="18.875px"
          textAlign="center"
          display="block"
          direction="column"
          justifyContent="unset"
          width="318px"
          height="unset"
          gap="unset"
          alignItems="unset"
          position="absolute"
          top="0%"
          bottom="0%"
          left="0%"
          right="0%"
          padding="0px 0px 0px 0px"
          whiteSpace="pre-wrap"
          children="電柱などに掲載する場合は、&#xA;電力会社などに許可を取ってください。"
          {...getOverrideProps(overrides, "check-caution608350")}
        ></Text>
      </View>
      <Text
        fontFamily="UD Digi Kyokasho NP-B"
        fontSize="13px"
        fontWeight="700"
        color="rgba(0,0,0,1)"
        lineHeight="15.03759765625px"
        textAlign="center"
        display="block"
        direction="column"
        justifyContent="unset"
        width="unset"
        height="unset"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="21.76%"
        bottom="75.65%"
        left="59.37%"
        right="34.31%"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="名前"
        {...getOverrideProps(overrides, "check-name")}
      ></Text>
      <Text
        fontFamily="UD Digi Kyokasho NP-B"
        fontSize="13px"
        fontWeight="700"
        color="rgba(0,0,0,1)"
        lineHeight="15.03759765625px"
        textAlign="center"
        display="block"
        direction="column"
        justifyContent="unset"
        width="unset"
        height="unset"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="60.62%"
        bottom="36.79%"
        left="15.57%"
        right="59.12%"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="迷子になった場所"
        {...getOverrideProps(overrides, "check-lostplace")}
      ></Text>
      <Text
        fontFamily="UD Digi Kyokasho NK-B"
        fontSize="13px"
        fontWeight="700"
        color="rgba(0,0,0,1)"
        lineHeight="15.03759765625px"
        textAlign="center"
        display="block"
        direction="column"
        justifyContent="unset"
        width="unset"
        height="unset"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="34.37%"
        bottom="63.04%"
        left="59.37%"
        right="34.31%"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="種類"
        {...getOverrideProps(overrides, "check-category")}
      ></Text>
      <Text
        fontFamily="UD Digi Kyokasho NK-B"
        fontSize="13px"
        fontWeight="700"
        color="rgba(0,0,0,1)"
        lineHeight="15.03759765625px"
        textAlign="center"
        display="block"
        direction="column"
        justifyContent="unset"
        width="unset"
        height="unset"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="40.59%"
        bottom="56.82%"
        left="59.37%"
        right="34.31%"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="年齢"
        {...getOverrideProps(overrides, "check-age")}
      ></Text>
      <Text
        fontFamily="UD Digi Kyokasho NK-B"
        fontSize="13px"
        fontWeight="700"
        color="rgba(0,0,0,1)"
        lineHeight="15.03759765625px"
        textAlign="center"
        display="block"
        direction="column"
        justifyContent="unset"
        width="unset"
        height="unset"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="46.8%"
        bottom="50.6%"
        left="59.37%"
        right="37.47%"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="色"
        {...getOverrideProps(overrides, "check-calor")}
      ></Text>
      <Text
        fontFamily="UD Digi Kyokasho NK-B"
        fontSize="13px"
        fontWeight="700"
        color="rgba(0,0,0,1)"
        lineHeight="15.03759765625px"
        textAlign="center"
        display="block"
        direction="column"
        justifyContent="unset"
        width="unset"
        height="unset"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="53.02%"
        bottom="44.39%"
        left="59.37%"
        right="34.31%"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="特徴"
        {...getOverrideProps(overrides, "check-feature")}
      ></Text>
      <Text
        fontFamily="UD Digi Kyokasho NK-B"
        fontSize="13px"
        fontWeight="700"
        color="rgba(0,0,0,1)"
        lineHeight="15.03759765625px"
        textAlign="center"
        display="block"
        direction="column"
        justifyContent="unset"
        width="unset"
        height="unset"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="28.15%"
        bottom="69.26%"
        left="59.37%"
        right="34.31%"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="種族"
        {...getOverrideProps(overrides, "check-animal")}
      ></Text>
      <Text
        fontFamily="Abhaya Libre ExtraBold"
        fontSize="13px"
        fontWeight="800"
        color="rgba(240,130,30,1)"
        lineHeight="15.3359375px"
        textAlign="center"
        display="block"
        direction="column"
        justifyContent="unset"
        width="151px"
        height="13px"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="0%"
        bottom="97.75%"
        left="34.31%"
        right="28.95%"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="かえっぺ"
        {...getOverrideProps(overrides, "\u304B\u3048\u3063\u307A")}
      ></Text>
      <Text
        fontFamily="Abhaya Libre ExtraBold"
        fontSize="48px"
        fontWeight="800"
        color="rgba(240,130,30,1)"
        lineHeight="56.625px"
        textAlign="center"
        display="block"
        direction="column"
        justifyContent="unset"
        width="220px"
        height="47px"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="1.21%"
        bottom="90.67%"
        left="26.03%"
        right="20.44%"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="KAEPET&#xA;"
        {...getOverrideProps(overrides, "title text")}
      ></Text>
      <View
        width="183px"
        height="281px"
        display="block"
        gap="unset"
        alignItems="unset"
        justifyContent="unset"
        position="absolute"
        top="11.4%"
        bottom="40.07%"
        left="13.38%"
        right="42.09%"
        padding="0px 0px 0px 0px"
        backgroundColor="rgba(217,217,217,1)"
        {...getOverrideProps(overrides, "check-petphoto")}
      ></View>
      <Image
        width="44.53%"
        height="48.53%"
        display="block"
        gap="unset"
        alignItems="unset"
        justifyContent="unset"
        position="absolute"
        top="11.4%"
        bottom="40.07%"
        left="13.38%"
        right="42.09%"
        padding="0px 0px 0px 0px"
        objectFit="cover"
        src={mainImage?.main}
        {...getOverrideProps(overrides, "Home_Cat_img")}
      ></Image>
      <Text
        fontFamily="Inter"
        fontSize="36px"
        fontWeight="600"
        color="rgba(0,18,176,1)"
        lineHeight="43.568180084228516px"
        textAlign="left"
        display="block"
        direction="column"
        justifyContent="unset"
        width="unset"
        height="unset"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="12.61%"
        bottom="78.76%"
        left="25.3%"
        right="20.92%"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="探しています"
        {...getOverrideProps(overrides, "check-title-lost")}
      ></Text>
    </View>
  );
}
