/***************************************************************************
 * The contents of this file were generated with Amplify Studio.           *
 * Please refrain from making any modifications to this file.              *
 * Any changes to this file will be overwritten when running amplify pull. *
 **************************************************************************/

/* eslint-disable */
import * as React from "react";
import { getOverrideProps, useNavigateAction } from "./utils";
import { Text, View } from "@aws-amplify/ui-react";
export default function TestExPosterPage(props) {
  const { poster, overrides, ...rest } = props;
  const creationnametextboxOnClick = useNavigateAction({ type: "reload" });
  return (
    <View
      width="356px"
      height="833px"
      display="block"
      gap="unset"
      alignItems="unset"
      justifyContent="unset"
      position="relative"
      padding="0px 0px 0px 0px"
      {...getOverrideProps(overrides, "TestExPosterPage")}
      {...rest}
    >
      <View
        width="151px"
        height="13px"
        display="block"
        gap="unset"
        alignItems="unset"
        justifyContent="unset"
        position="absolute"
        top="0%"
        bottom="98.44%"
        left="32.87%"
        right="24.72%"
        padding="0px 0px 0px 0px"
        {...getOverrideProps(overrides, "\u304B\u3048\u3063\u307A649188")}
      >
        <Text
          fontFamily="Abhaya Libre ExtraBold"
          fontSize="13px"
          fontWeight="800"
          color="rgba(240,130,30,1)"
          lineHeight="15.3359375px"
          textAlign="center"
          display="block"
          direction="column"
          justifyContent="unset"
          width="151px"
          height="13px"
          gap="unset"
          alignItems="unset"
          position="absolute"
          top="0%"
          bottom="0%"
          left="0%"
          right="0%"
          padding="0px 0px 0px 0px"
          whiteSpace="pre-wrap"
          children="かえっぺ"
          {...getOverrideProps(overrides, "\u304B\u3048\u3063\u307A649189")}
        ></Text>
      </View>
      <View
        width="356px"
        height="822px"
        display="block"
        gap="unset"
        alignItems="unset"
        justifyContent="unset"
        position="absolute"
        top="1.32%"
        bottom="0%"
        left="0%"
        right="0%"
        padding="0px 0px 0px 0px"
        {...getOverrideProps(overrides, "Component 13")}
      >
        <View
          width="330px"
          height="29px"
          display="block"
          gap="unset"
          alignItems="unset"
          justifyContent="unset"
          position="absolute"
          top="29.44%"
          bottom="67.03%"
          left="7.3%"
          right="0%"
          padding="0px 0px 0px 0px"
          {...getOverrideProps(overrides, "PosterDate")}
        >
          <View
            width="330px"
            height="29px"
            display="block"
            gap="unset"
            alignItems="unset"
            justifyContent="unset"
            position="absolute"
            top="0%"
            bottom="0%"
            left="0%"
            right="0%"
            border="1px SOLID rgba(212,212,212,1)"
            borderRadius="6px"
            padding="0px 0px 0px 0px"
            backgroundColor="rgba(255,255,255,1)"
            {...getOverrideProps(overrides, "Creation-lostd&t-textbox")}
          ></View>
          <Text
            fontFamily="Abhaya Libre ExtraBold"
            fontSize="14px"
            fontWeight="800"
            color="rgba(181,181,181,1)"
            lineHeight="16.515625px"
            textAlign="left"
            display="block"
            direction="column"
            justifyContent="unset"
            width="230px"
            height="14px"
            gap="unset"
            alignItems="unset"
            position="absolute"
            top="20.69%"
            bottom="31.03%"
            left="2.12%"
            right="28.18%"
            padding="0px 0px 0px 0px"
            whiteSpace="pre-wrap"
            children="YY/MM/DD"
            {...getOverrideProps(overrides, "YY/MM/DD")}
          ></Text>
        </View>
        <View
          width="161px"
          height="38px"
          display="block"
          gap="unset"
          alignItems="unset"
          justifyContent="unset"
          position="absolute"
          top="95.38%"
          bottom="0%"
          left="30.34%"
          right="24.44%"
          padding="0px 0px 0px 0px"
          {...getOverrideProps(overrides, "PosterImageButton")}
        >
          <View
            width="116px"
            height="38px"
            display="block"
            gap="unset"
            alignItems="unset"
            justifyContent="unset"
            position="absolute"
            top="0%"
            bottom="0%"
            left="15.53%"
            right="12.42%"
            padding="0px 0px 0px 0px"
            {...getOverrideProps(overrides, "T_SigU_Sub_Button")}
          >
            <View
              width="168px"
              height="38px"
              display="block"
              gap="unset"
              alignItems="unset"
              justifyContent="unset"
              position="absolute"
              top="0%"
              bottom="0%"
              left="-22.41%"
              right="-22.41%"
              border="1px SOLID rgba(172,172,172,1)"
              borderRadius="6px"
              padding="0px 0px 0px 0px"
              backgroundColor="rgba(255,243,180,1)"
              {...getOverrideProps(overrides, "T_SigU_Sub_Box")}
            ></View>
          </View>
          <Text
            fontFamily="Inter"
            fontSize="16px"
            fontWeight="400"
            color="rgba(0,0,0,1)"
            lineHeight="19.363636016845703px"
            textAlign="center"
            display="block"
            direction="column"
            justifyContent="unset"
            width="161px"
            height="unset"
            gap="unset"
            alignItems="unset"
            position="absolute"
            top="26.32%"
            bottom="23.68%"
            left="0%"
            right="0%"
            padding="0px 0px 0px 0px"
            whiteSpace="pre-wrap"
            children="イメージを見る"
            {...getOverrideProps(overrides, "T_SigU_Sub_Text")}
          ></Text>
        </View>
        <View
          width="168px"
          height="38px"
          display="block"
          gap="unset"
          alignItems="unset"
          justifyContent="unset"
          position="absolute"
          top="13.87%"
          bottom="81.51%"
          left="28.37%"
          right="24.44%"
          padding="0px 0px 0px 0px"
          {...getOverrideProps(overrides, "PosterPicButton")}
        >
          <View
            width="168px"
            height="38px"
            display="block"
            gap="unset"
            alignItems="unset"
            justifyContent="unset"
            position="absolute"
            top="0%"
            bottom="0%"
            left="0%"
            right="0%"
            border="1px SOLID rgba(172,172,172,1)"
            borderRadius="6px"
            padding="0px 0px 0px 0px"
            backgroundColor="rgba(255,243,180,1)"
            {...getOverrideProps(overrides, "PosterChoosePic")}
          ></View>
          <Text
            fontFamily="Inter"
            fontSize="16px"
            fontWeight="400"
            color="rgba(0,0,0,1)"
            lineHeight="19.363636016845703px"
            textAlign="center"
            display="block"
            direction="column"
            justifyContent="unset"
            width="161px"
            height="unset"
            gap="unset"
            alignItems="unset"
            position="absolute"
            top="26.32%"
            bottom="23.68%"
            left="4.17%"
            right="0%"
            padding="0px 0px 0px 0px"
            whiteSpace="pre-wrap"
            children="写真を選択"
            {...getOverrideProps(overrides, "PosterCosePic")}
          ></Text>
        </View>
        <View
          width="330px"
          height="91px"
          display="block"
          gap="unset"
          alignItems="unset"
          justifyContent="unset"
          position="absolute"
          top="80.29%"
          bottom="8.64%"
          left="7.3%"
          right="0%"
          padding="0px 0px 0px 0px"
          {...getOverrideProps(overrides, "PosterEtc")}
        >
          <View
            width="330px"
            height="91px"
            display="block"
            gap="unset"
            alignItems="unset"
            justifyContent="unset"
            position="absolute"
            top="0%"
            bottom="0%"
            left="0%"
            right="0%"
            border="1px SOLID rgba(212,212,212,1)"
            borderRadius="6px"
            padding="0px 0px 0px 0px"
            backgroundColor="rgba(255,255,255,1)"
            {...getOverrideProps(overrides, "Creation-remarks-textbox")}
          ></View>
        </View>
        <View
          width="330px"
          height="30px"
          display="block"
          gap="unset"
          alignItems="unset"
          justifyContent="unset"
          position="absolute"
          top="72.63%"
          bottom="23.72%"
          left="7.3%"
          right="0%"
          padding="0px 0px 0px 0px"
          {...getOverrideProps(overrides, "PosterFeature")}
        >
          <View
            width="330px"
            height="30px"
            display="block"
            gap="unset"
            alignItems="unset"
            justifyContent="unset"
            position="absolute"
            top="0%"
            bottom="0%"
            left="0%"
            right="0%"
            border="1px SOLID rgba(212,212,212,1)"
            borderRadius="6px"
            padding="0px 0px 0px 0px"
            backgroundColor="rgba(255,255,255,1)"
            {...getOverrideProps(overrides, "Creation-feature-textbox")}
          ></View>
        </View>
        <View
          width="330px"
          height="29px"
          display="block"
          gap="unset"
          alignItems="unset"
          justifyContent="unset"
          position="absolute"
          top="65.21%"
          bottom="31.27%"
          left="7.3%"
          right="0%"
          padding="0px 0px 0px 0px"
          {...getOverrideProps(overrides, "PosterColor")}
        >
          <View
            width="330px"
            height="29px"
            display="block"
            gap="unset"
            alignItems="unset"
            justifyContent="unset"
            position="absolute"
            top="0%"
            bottom="0%"
            left="0%"
            right="0%"
            border="1px SOLID rgba(212,212,212,1)"
            borderRadius="6px"
            padding="0px 0px 0px 0px"
            backgroundColor="rgba(255,255,255,1)"
            {...getOverrideProps(overrides, "Creation-color-textbox")}
          ></View>
        </View>
        <View
          width="330px"
          height="29px"
          display="block"
          gap="unset"
          alignItems="unset"
          justifyContent="unset"
          position="absolute"
          top="58.39%"
          bottom="38.08%"
          left="7.3%"
          right="0%"
          padding="0px 0px 0px 0px"
          {...getOverrideProps(overrides, "PosterAge")}
        >
          <View
            width="330px"
            height="29px"
            display="block"
            gap="unset"
            alignItems="unset"
            justifyContent="unset"
            position="absolute"
            top="0%"
            bottom="0%"
            left="0%"
            right="0%"
            border="1px SOLID rgba(212,212,212,1)"
            borderRadius="6px"
            padding="0px 0px 0px 0px"
            backgroundColor="rgba(255,255,255,1)"
            {...getOverrideProps(overrides, "Creation-age-textbox")}
          ></View>
        </View>
        <View
          width="330px"
          height="30px"
          display="block"
          gap="unset"
          alignItems="unset"
          justifyContent="unset"
          position="absolute"
          top="51.22%"
          bottom="45.13%"
          left="7.3%"
          right="0%"
          padding="0px 0px 0px 0px"
          {...getOverrideProps(overrides, "PosterType")}
        >
          <View
            width="330px"
            height="30px"
            display="block"
            gap="unset"
            alignItems="unset"
            justifyContent="unset"
            position="absolute"
            top="0%"
            bottom="0%"
            left="0%"
            right="0%"
            border="1px SOLID rgba(212,212,212,1)"
            borderRadius="6px"
            padding="0px 0px 0px 0px"
            backgroundColor="rgba(255,255,255,1)"
            {...getOverrideProps(overrides, "Creation-catrgory-textbox")}
          ></View>
          <Text
            fontFamily="Abhaya Libre ExtraBold"
            fontSize="14px"
            fontWeight="800"
            color="rgba(181,181,181,1)"
            lineHeight="16.515625px"
            textAlign="left"
            display="block"
            direction="column"
            justifyContent="unset"
            width="287px"
            height="17px"
            gap="unset"
            alignItems="unset"
            position="absolute"
            top="20%"
            bottom="23.33%"
            left="2.12%"
            right="10.91%"
            padding="0px 0px 0px 0px"
            whiteSpace="pre-wrap"
            children="例：シェパード、アメリカンショートヘア"
            {...getOverrideProps(overrides, "Creation-catrgory-Ex")}
          ></Text>
        </View>
        <View
          width="330px"
          height="29px"
          display="block"
          gap="unset"
          alignItems="unset"
          justifyContent="unset"
          position="absolute"
          top="44.4%"
          bottom="52.07%"
          left="7.3%"
          right="0%"
          padding="0px 0px 0px 0px"
          {...getOverrideProps(overrides, "PosterAnimal")}
        >
          <View
            width="330px"
            height="29px"
            display="block"
            gap="unset"
            alignItems="unset"
            justifyContent="unset"
            position="absolute"
            top="0%"
            bottom="0%"
            left="0%"
            right="0%"
            border="1px SOLID rgba(212,212,212,1)"
            borderRadius="6px"
            padding="0px 0px 0px 0px"
            backgroundColor="rgba(255,255,255,1)"
            {...getOverrideProps(overrides, "Creation-aniimal-textbox")}
          ></View>
          <Text
            fontFamily="Abhaya Libre ExtraBold"
            fontSize="14px"
            fontWeight="800"
            color="rgba(181,181,181,1)"
            lineHeight="16.515625px"
            textAlign="left"
            display="block"
            direction="column"
            justifyContent="unset"
            width="230px"
            height="14px"
            gap="unset"
            alignItems="unset"
            position="absolute"
            top="27.59%"
            bottom="24.14%"
            left="1.82%"
            right="28.48%"
            padding="0px 0px 0px 0px"
            whiteSpace="pre-wrap"
            children="例：犬、猫、鳥"
            {...getOverrideProps(overrides, "Creation-aniimal-Ex")}
          ></Text>
        </View>
        <View
          width="330px"
          height="29px"
          display="block"
          gap="unset"
          alignItems="unset"
          justifyContent="unset"
          position="absolute"
          top="36.86%"
          bottom="59.61%"
          left="7.3%"
          right="0%"
          padding="0px 0px 0px 0px"
          {...getOverrideProps(overrides, "PosterPlace")}
        >
          <View
            width="330px"
            height="29px"
            display="block"
            gap="unset"
            alignItems="unset"
            justifyContent="unset"
            position="absolute"
            top="0%"
            bottom="0%"
            left="0%"
            right="0%"
            border="1px SOLID rgba(212,212,212,1)"
            borderRadius="6px"
            padding="0px 0px 0px 0px"
            backgroundColor="rgba(255,255,255,1)"
            {...getOverrideProps(overrides, "Creation-lostplace-textbox")}
          ></View>
          <Text
            fontFamily="Abhaya Libre ExtraBold"
            fontSize="14px"
            fontWeight="800"
            color="rgba(181,181,181,1)"
            lineHeight="16.515625px"
            textAlign="left"
            display="block"
            direction="column"
            justifyContent="unset"
            width="230px"
            height="17px"
            gap="unset"
            alignItems="unset"
            position="absolute"
            top="20.69%"
            bottom="20.69%"
            left="1.82%"
            right="28.48%"
            padding="0px 0px 0px 0px"
            whiteSpace="pre-wrap"
            children="例：2丁目郵便局付近、〇〇公園"
            {...getOverrideProps(overrides, "Creation-lostplace-Ex")}
          ></Text>
        </View>
        <View
          width="330px"
          height="29px"
          display="block"
          gap="unset"
          alignItems="unset"
          justifyContent="unset"
          position="absolute"
          top="22.51%"
          bottom="73.97%"
          left="7.3%"
          right="0%"
          padding="0px 0px 0px 0px"
          {...getOverrideProps(overrides, "PosterName")}
        >
          <View
            width="330px"
            height="29px"
            display="block"
            gap="unset"
            alignItems="unset"
            justifyContent="unset"
            position="absolute"
            top="0%"
            bottom="0%"
            left="0%"
            right="0%"
            border="1px SOLID rgba(212,212,212,1)"
            borderRadius="6px"
            padding="0px 0px 0px 0px"
            backgroundColor="rgba(255,255,255,1)"
            onClick={() => {
              creationnametextboxOnClick();
            }}
            {...getOverrideProps(overrides, "Creation-name-textbox")}
          ></View>
          <Text
            fontFamily="Abhaya Libre ExtraBold"
            fontSize="14px"
            fontWeight="800"
            color="rgba(181,181,181,1)"
            lineHeight="16.515625px"
            textAlign="left"
            display="block"
            direction="column"
            justifyContent="unset"
            width="230px"
            height="17px"
            gap="unset"
            alignItems="unset"
            position="absolute"
            top="20.69%"
            bottom="20.69%"
            left="1.21%"
            right="29.09%"
            padding="0px 0px 0px 0px"
            whiteSpace="pre-wrap"
            children="例：ラッキー、太郎、モカ"
            {...getOverrideProps(overrides, "Creation-name-Ex")}
          ></Text>
        </View>
        <View
          width="100px"
          height="24px"
          display="block"
          gap="unset"
          alignItems="unset"
          justifyContent="unset"
          position="absolute"
          top="6.81%"
          bottom="90.27%"
          left="37.64%"
          right="34.27%"
          padding="0px 0px 0px 0px"
          {...getOverrideProps(overrides, "Creation-info649221")}
        >
          <Text
            fontFamily="Inter"
            fontSize="20px"
            fontWeight="400"
            color="rgba(28,25,25,1)"
            lineHeight="24.204544067382812px"
            textAlign="center"
            display="block"
            direction="column"
            justifyContent="unset"
            width="unset"
            height="unset"
            gap="unset"
            alignItems="unset"
            position="absolute"
            top="0%"
            bottom="0%"
            left="0%"
            right="0%"
            padding="0px 0px 0px 0px"
            whiteSpace="pre-wrap"
            children="ペット情報"
            {...getOverrideProps(overrides, "Creation-info649222")}
          ></Text>
        </View>
        <Text
          fontFamily="Abhaya Libre ExtraBold"
          fontSize="48px"
          fontWeight="800"
          color="rgba(240,130,30,1)"
          lineHeight="56.625px"
          textAlign="center"
          display="block"
          direction="column"
          justifyContent="unset"
          width="261px"
          height="47px"
          gap="unset"
          alignItems="unset"
          position="absolute"
          top="0%"
          bottom="94.28%"
          left="14.33%"
          right="12.36%"
          padding="0px 0px 0px 0px"
          whiteSpace="pre-wrap"
          children="KAEPET&#xA;"
          {...getOverrideProps(overrides, "title text")}
        ></Text>
        <Text
          fontFamily="Inter"
          fontSize="16px"
          fontWeight="400"
          color="rgba(28,25,25,1)"
          lineHeight="19.363636016845703px"
          textAlign="center"
          display="block"
          direction="column"
          justifyContent="unset"
          width="86px"
          height="17px"
          gap="unset"
          alignItems="unset"
          position="absolute"
          top="41%"
          bottom="56.93%"
          left="7.02%"
          right="68.82%"
          padding="0px 0px 0px 0px"
          whiteSpace="pre-wrap"
          children="動物の種類"
          {...getOverrideProps(overrides, "Creation-animal")}
        ></Text>
        <View
          width="32px"
          height="17px"
          display="block"
          gap="unset"
          alignItems="unset"
          justifyContent="unset"
          position="absolute"
          top="55.47%"
          bottom="42.46%"
          left="8.99%"
          right="82.02%"
          padding="0px 0px 0px 0px"
          {...getOverrideProps(overrides, "Creation-age649225")}
        >
          <Text
            fontFamily="Inter"
            fontSize="16px"
            fontWeight="400"
            color="rgba(28,25,25,1)"
            lineHeight="19.363636016845703px"
            textAlign="center"
            display="block"
            direction="column"
            justifyContent="unset"
            width="32px"
            height="17px"
            gap="unset"
            alignItems="unset"
            position="absolute"
            top="0%"
            bottom="0%"
            left="0%"
            right="0%"
            padding="0px 0px 0px 0px"
            whiteSpace="pre-wrap"
            children="年齢"
            {...getOverrideProps(overrides, "Creation-age649226")}
          ></Text>
        </View>
        <View
          width="32px"
          height="17px"
          display="block"
          gap="unset"
          alignItems="unset"
          justifyContent="unset"
          position="absolute"
          top="62.41%"
          bottom="35.52%"
          left="7.02%"
          right="83.99%"
          padding="0px 0px 0px 0px"
          {...getOverrideProps(overrides, "Creation-age649227")}
        >
          <Text
            fontFamily="Inter"
            fontSize="16px"
            fontWeight="400"
            color="rgba(28,25,25,1)"
            lineHeight="19.363636016845703px"
            textAlign="center"
            display="block"
            direction="column"
            justifyContent="unset"
            width="32px"
            height="17px"
            gap="unset"
            alignItems="unset"
            position="absolute"
            top="0%"
            bottom="0%"
            left="0%"
            right="0%"
            padding="0px 0px 0px 0px"
            whiteSpace="pre-wrap"
            children="色"
            {...getOverrideProps(overrides, "Creation-age649228")}
          ></Text>
        </View>
        <Text
          fontFamily="Inter"
          fontSize="16px"
          fontWeight="400"
          color="rgba(28,25,25,1)"
          lineHeight="19.363636016845703px"
          textAlign="center"
          display="block"
          direction="column"
          justifyContent="unset"
          width="96px"
          height="16px"
          gap="unset"
          alignItems="unset"
          position="absolute"
          top="77.49%"
          bottom="20.56%"
          left="0%"
          right="73.03%"
          padding="0px 0px 0px 0px"
          whiteSpace="pre-wrap"
          children="備考"
          {...getOverrideProps(overrides, "Creation-remarks")}
        ></Text>
        <View
          width="32px"
          height="17px"
          display="block"
          gap="unset"
          alignItems="unset"
          justifyContent="unset"
          position="absolute"
          top="70.07%"
          bottom="27.86%"
          left="8.99%"
          right="82.02%"
          padding="0px 0px 0px 0px"
          {...getOverrideProps(overrides, "Creation-feature649230")}
        >
          <Text
            fontFamily="Inter"
            fontSize="16px"
            fontWeight="400"
            color="rgba(28,25,25,1)"
            lineHeight="19.363636016845703px"
            textAlign="center"
            display="block"
            direction="column"
            justifyContent="unset"
            width="32px"
            height="17px"
            gap="unset"
            alignItems="unset"
            position="absolute"
            top="0%"
            bottom="0%"
            left="0%"
            right="0%"
            padding="0px 0px 0px 0px"
            whiteSpace="pre-wrap"
            children="特徴"
            {...getOverrideProps(overrides, "Creation-feature649231")}
          ></Text>
        </View>
        <View
          width="32px"
          height="17px"
          display="block"
          gap="unset"
          alignItems="unset"
          justifyContent="unset"
          position="absolute"
          top="48.54%"
          bottom="49.39%"
          left="8.99%"
          right="82.02%"
          padding="0px 0px 0px 0px"
          {...getOverrideProps(overrides, "Creation-category649232")}
        >
          <Text
            fontFamily="Inter"
            fontSize="16px"
            fontWeight="400"
            color="rgba(28,25,25,1)"
            lineHeight="19.363636016845703px"
            textAlign="center"
            display="block"
            direction="column"
            justifyContent="unset"
            width="32px"
            height="17px"
            gap="unset"
            alignItems="unset"
            position="absolute"
            top="0%"
            bottom="0%"
            left="0%"
            right="0%"
            padding="0px 0px 0px 0px"
            whiteSpace="pre-wrap"
            children="種類"
            {...getOverrideProps(overrides, "Creation-category649233")}
          ></Text>
        </View>
        <View
          width="128px"
          height="19px"
          display="block"
          gap="unset"
          alignItems="unset"
          justifyContent="unset"
          position="absolute"
          top="34.18%"
          bottom="63.5%"
          left="7.87%"
          right="56.18%"
          padding="0px 0px 0px 0px"
          {...getOverrideProps(overrides, "Creation-lostplace649234")}
        >
          <Text
            fontFamily="Inter"
            fontSize="16px"
            fontWeight="400"
            color="rgba(0,0,0,1)"
            lineHeight="19.363636016845703px"
            textAlign="center"
            display="block"
            direction="column"
            justifyContent="unset"
            width="unset"
            height="unset"
            gap="unset"
            alignItems="unset"
            position="absolute"
            top="0%"
            bottom="0%"
            left="0%"
            right="0%"
            padding="0px 0px 0px 0px"
            whiteSpace="pre-wrap"
            children="迷子になった場所"
            {...getOverrideProps(overrides, "Creation-lostplace649235")}
          ></Text>
        </View>
        <View
          width="32px"
          height="17px"
          display="block"
          gap="unset"
          alignItems="unset"
          justifyContent="unset"
          position="absolute"
          top="19.46%"
          bottom="78.47%"
          left="8.15%"
          right="82.87%"
          padding="0px 0px 0px 0px"
          {...getOverrideProps(overrides, "Creation-name649236")}
        >
          <Text
            fontFamily="Inter"
            fontSize="16px"
            fontWeight="400"
            color="rgba(28,25,25,1)"
            lineHeight="19.363636016845703px"
            textAlign="center"
            display="block"
            direction="column"
            justifyContent="unset"
            width="32px"
            height="17px"
            gap="unset"
            alignItems="unset"
            position="absolute"
            top="0%"
            bottom="0%"
            left="0%"
            right="0%"
            padding="0px 0px 0px 0px"
            whiteSpace="pre-wrap"
            children="名前"
            {...getOverrideProps(overrides, "Creation-name649237")}
          ></Text>
        </View>
        <View
          width="160px"
          height="23px"
          display="block"
          gap="unset"
          alignItems="unset"
          justifyContent="unset"
          position="absolute"
          top="26.4%"
          bottom="70.8%"
          left="3.65%"
          right="51.4%"
          padding="0px 0px 0px 0px"
          {...getOverrideProps(overrides, "Creation-lostd&t649238")}
        >
          <Text
            fontFamily="Inter"
            fontSize="16px"
            fontWeight="400"
            color="rgba(0,0,0,1)"
            lineHeight="19.363636016845703px"
            textAlign="center"
            display="block"
            direction="column"
            justifyContent="unset"
            width="160px"
            height="23px"
            gap="unset"
            alignItems="unset"
            position="absolute"
            top="0%"
            bottom="0%"
            left="0%"
            right="0%"
            padding="0px 0px 0px 0px"
            whiteSpace="pre-wrap"
            children="迷子になった日時"
            {...getOverrideProps(overrides, "Creation-lostd&t649239")}
          ></Text>
        </View>
      </View>
    </View>
  );
}
